self:
  peer_id: peer2
model:
  path: ~/models/Llama-3.2-3B-Instruct-uncensored-Q5_K_S.gguf
  n_ctx: 4096
  n_threads: 8
  n_gpu_layers: 0
  max_tokens: 256
signing:
  enabled: true
  key_env: HOSPITAL_FEDERATOR_HMAC_KEY
  alg: sha256
tls_defaults:
  verify: /home/user/hospital_federator/certs/ca/ca.crt
  timeout_s: 5.0
  client_cert: /home/user/hospital_federator/certs/peer2/peer2.crt
  client_key: /home/user/hospital_federator/certs/peer2/peer2.key
peers:
- id: peer1
  name: Hospital 1
  url: https://127.0.0.1:8000
- id: peer2
  name: Hospital 2
  url: https://127.0.0.1:8001
  tls:
    client_cert: /home/user/hospital_federator/certs/peer2/peer2.crt
    client_key: /home/user/hospital_federator/certs/peer2/peer2.key
- id: peer3
  name: Hospital 3
  url: https://127.0.0.1:8002
